### ISSUE TITLE
Supervisor start error. 

### ISSUE THREAD

**Issue by niranjan92** [morninj/django-docker#16]
I did all the configuration and then 

docker run -d -p 80:80 -v $(pwd):/code --env DJANGO_PRODUCTION=false <yourname>/django-docker

On running docker, the container is spawned, but supervisor cannot start the service. I am getting following error: 

2016-05-01T22:05:58.420603194Z 2016-05-01 22:05:58,420 INFO exited: initialize (exit status 127; not expected)
2016-05-01T22:05:59.423536295Z 2016-05-01 22:05:59,423 INFO spawned: 'initialize' with pid 102
2016-05-01T22:05:59.427550188Z 2016-05-01 22:05:59,427 INFO success: initialize entered RUNNING state, process has stayed up for

> than 0 seconds (startsecs)
> 2016-05-01T22:05:59.428110966Z 2016-05-01 22:05:59,428 INFO exited: initialize (exit status 127; not expected)
> 2016-05-01T22:06:00.431900979Z 2016-05-01 22:06:00,430 INFO spawned: 'initialize' with pid 103
> 2016-05-01T22:06:00.435845297Z 2016-05-01 22:06:00,435 INFO success: initialize entered RUNNING state, process has stayed up for
> than 0 seconds (startsecs)
> 2016-05-01T22:06:00.436428078Z 2016-05-01 22:06:00,436 INFO exited: initialize (exit status 127; not expected)
> 2016-05-01T22:06:01.439192191Z 2016-05-01 22:06:01,438 INFO spawned: 'initialize' with pid 104
> 2016-05-01T22:06:01.443373806Z 2016-05-01 22:06:01,443 INFO success: initialize entered RUNNING state, process has stayed up for
> than 0 seconds (startsecs)

I looked into initialize.sh script but couldn't figure out the issue. Can you please help me debug this?

**Comment by morninj** [comment]
Fixed in https://github.com/morninj/django-docker/pull/21
