### ISSUE TITLE
bind-mounting with `docker run` and the -v parameter only works on Linux with extra setup

### ISSUE THREAD

**Issue by nmgeek** [morninj/django-docker#17]
In the README section on the development setup I followed your instructions but could not get the local files mounted in the container.  So the container never ran gunicorn.

After a good deal of research I found that boot2docker, the system running in the docker-machine VM, looks for a share folder named /Users on the host and only allows you to bind-mount files under /User.  So to make this work you have to define a share folder in VirtualBox called /Users then the -v argument would have to always specify the local path as being starting with /Users.

The README makes no mention of this.  How did you ever get that -v bind-mount option to work?  Your host was running Linux, right?

**Comment by morninj** [comment]
Sorry for the slow reply. (Email alerts were turned off for new issues, so I didn't see this until just now.)

It sounds like you tried to run the code somewhere other than under the `/Users` directory. The README addresses this towards the beginning, where it says:

    Mac users should clone it to a directory under /Users because of a Docker bug involving Mac shared directories.

With that, the `-v` flag works fine on Mac OS X. On Ubuntu, the `-v` flag seems to work regardless of where the code is stored.
