### ISSUE TITLE
import patterns in urls.py doesn't work with django 1.10

### ISSUE THREAD

**Issue by hannah98** [morninj/django-docker#19]
The `requirements.txt` file doesn't specify versions so running this installs django 1.10.  The `urls.py` file imports `patterns` from `django.conf.urls`, but `patterns` has been deprecated.  Explicitly setting the version of django in the `requirements.txt` file (to a version lower than 1.10) fixed this issue for me.

**Comment by nathang21** [comment]
Also confirmed this issue. I was able to get it working with 1.10 by following the new convention for views  & url patterns.

**Comment by morninj** [comment]
Fixed in https://github.com/morninj/django-docker/commit/4a8aaf3c9e1da5fd10580cc5a3859d801f2c9553
