### ISSUE TITLE
Updating models or files and deployement

### ISSUE THREAD

**Issue by afshinm** [morninj/django-docker#22]
Hey, 

First of all, thanks for this repo. Looks really good. One thing that I can't completely understand about your development and deployment workflow is that what would happen when I have a container deployed on the production server and then I have changed some models and I want to deploy them.

Obviously, current Dockerfile is going to install a new mysql instance which doesn't have the old data on the previous container so `makemigrations` won't be useful in this case.

Could you please explain what is the right workflow in this scenario?

**Comment by morninj** [comment]
> current Dockerfile is going to install a new mysql instance which doesn't have the old data on the previous container so makemigrations won't be useful in this case.

Not quite. It will only install a new local MySQL instance in the _development_ environment. In _production_, it will connect to an external database server. You specify the production database in `config.ini` in these lines:

    DATABASE_HOST = 0.0.0.0         ; IP address of your database server
    DATABASE_USERNAME = root
    DATABASE_PASSWORD = rootpassword
    DATABASE_NAME = django
